# parameters
payload_ACF = 34 # 1/10 kg # heavy tool

global acc_grind = 0.7 # m/s^2
global vel_grind = 0.1 # 0.25 # m/s
global t_sleep = 6 # s

# stopping
global acc_stop = 50 # m/s^2


# initial pose (check installation variables!)
rotvec_init = rpy2rotvec([d2r(rpy_contact_ACF[0]), d2r(rpy_contact_ACF[1]), d2r(rpy_contact_ACF[2])])
global p_init = p[pos_contact_ACF[0], pos_contact_ACF[1], pos_contact_ACF[2], rotvec_init[0], rotvec_init[1], rotvec_init[2]]

# init ACF payload
modbus_set_output_register("set_payload_ACF", payload_ACF)